language: "en-US"
reviews:
  auto_review:
    enabled: true
    auto_incremental_review: true
  request_changes_workflow: true
  high_level_summary: true
  review_status: true
  auto_resolve: true
  abort_on_close: true
chat:
  auto_reply: true
