name: CI/CD Pipeline with CodeRabbit

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI application
        run: |
          python -m uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Give the server some time to start

      - name: Run health check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/health)
          if [ $response = "200" ]; then
            echo "Health check passed"
          else
            echo "Health check failed"
            exit 1
          fi

  wait_for_coderabbit:
    needs: build_and_check
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CodeRabbit Review
        uses: fountainhead/action-wait-for-check@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: CodeRabbit
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

  deploy:
    needs: wait_for_coderabbit
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to production
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Add your deployment commands here
          # For example:
          # python deploy_script.py
          echo "Deploying to production..."

      - name: Post-deployment checks
        run: |
          # Add any post-deployment checks here
          # For example:
          # python health_check.py
          echo "Running post-deployment checks..."